Bootstrap CRUD operations for Projects and Characters
EnginnTechnologies/enginn-rb pull request #1
Opened 2022-01-28 15:58 UTC by durierem

2022-02-01 14:01 UTC, durierem commented on lib/enginn/resource.rb
> +      # TODO: find a way to properly notice the user that the deletion succeeded
Même remarque pour les autres opérations.
S'il y a une erreur, une exception est levée dans tous les cas. Mais ce serait peut-être intéressant d'avoir d'autres moyens de signifier un succès ou un échec.

2022-02-01 14:03 UTC, durierem commented on lib/enginn/resource_index.rb
> +      @pagination = { current: 1 } # Reset pagination to avoid messing with last run's
Réinitialisation de la pagination pour éviter ça :
```ruby
characters.per(1).page(2).fetch! # => Renvoie la 2ème page contenant 1 seul personnage [OK]
characters.each do { |character| ... } # => Démarre à partir de la 2ème page (puisque défini comme tel précédemment) [FAIL]
```
Mais du coup ça rend `#per` et `#page` inutiles en dehors d'un simple `#fetch!` manuel. Interface à discuter et repréciser ?

2022-02-01 14:06 UTC, durierem commented on lib/enginn/resource_index.rb
> +      raise NotImplementedError # REVIEW: not sure this is intended to be directly used...
Autre méthode : supprimer `ResourceIndex.resource` et Ruby lèvera tout seul un `NoMethodError`. C'est probablement la manière la plus idiomatique d'implémenter ça mais du coup on ne peut pas proprement documenter la méthode en question.

2022-02-04 13:15 UTC, levraipixel commented on README.md
> +characters = project.characters(gender_eq: 'male') # fitlers
typo dans le commentaire

2022-02-04 13:28 UTC, levraipixel commented on bin/console
>  # frozen_string_literal: true
Il sert à quoi, ce fichier ?

2022-02-04 13:29 UTC, durierem commented on bin/console
>  # frozen_string_literal: true
Si tu lances `bin/console` tu as un IRB avec une client déjà initialisé. C'est pour faciliter le développement et les tests au lieu d'avoir à réinstaller la gem manuellement ou se débrouiller avec d'autres fichiers et des require locaux.
D'où la présence des variables d'ENV pour redéfinir le endpoint à utiliser (staging par exemple) et un api token

2022-02-04 13:37 UTC, durierem commented on README.md
> +characters = project.characters(gender_eq: 'male') # fitlers
Oups, j'ai pas mis à jour le README, les instrutions pour les filtres ne sont plus bonnes.

2022-02-04 13:56 UTC, levraipixel requested changes

2022-02-04 13:56 UTC, levraipixel commented on lib/enginn/project.rb
> +      # TODO: replace `uid` with `id` when PK migration is completed
Ça c'est bon, du coup, non ?

2022-02-04 13:56 UTC, levraipixel commented on lib/enginn/resource.rb
> +      # TODO: find a way to properly notice the user that the deletion succeeded
Est-ce qu'on ne proposerait pas une méthode `destroy` qui répondrait `true` ou `false` comme avec ActiveRecord ?

2022-02-04 13:56 UTC, levraipixel commented on lib/enginn/resource.rb
> +        self.class.define_method(attribute) { @attributes[attribute] }
Tu as préféré définir des méthodes à la volée plutôt que d'utiliser `method_missing`, c'est ça ?

2022-02-04 13:56 UTC, levraipixel commented on lib/enginn/resource.rb
> +        instance_variable_set("@#{attribute}", value)
Pourquoi est-ce que tu es obligé de maintenir `@attributes` ET des variables d'instance ?

2022-02-04 13:56 UTC, levraipixel commented on bin/console
>  # frozen_string_literal: true
ok compris, merci 👍🏻

2022-02-04 13:56 UTC, levraipixel commented on spec/enginn/client_spec.rb
> +  describe '#projects' do
Je rajouterais un truc pour tester que ça n'effectue pas encore de requête, t'en penses quoi ?

2022-02-04 13:56 UTC, levraipixel commented on spec/enginn/resource_index_spec.rb
> +      # conn.response :logger
Peut-être plutôt avec une variable d'env du type `DEBUG_STUBS`, dans ce cas, non ?

2022-02-04 14:31 UTC, durierem commented on lib/enginn/resource.rb
> +        instance_variable_set("@#{attribute}", value)
Principalement un résidu de précédentes phases de développement x)

Mais en vrai, c'est plus simple pour gérer les requêtes ensuite (voir `Resource#request`) Je prends tout ce qui est dans `@attributes` au lieu de filtrer d'autres attributs qui pourraient exister (comme `@project`). Ça permet aussi d'avoir un fallback plus manuel.

2022-02-04 14:33 UTC, durierem commented on spec/enginn/resource_index_spec.rb
> +      # conn.response :logger
Bof. Je l'ai laissé comme moyen simple à un futur dév d'afficher les requêtes étant donné que j'ai un peu galéré avec les stubs. C'est pas spécialement plus pratique de passer par une variable d'env je trouve.

2022-02-04 15:14 UTC, durierem commented on lib/enginn/resource.rb
> +        self.class.define_method(attribute) { @attributes[attribute] }
Je ne connaissais pas `method_missing` mais ça semble plutôt convenir quand on veut définir un comportement lorsqu'on a pas de méthode. Là en l'occurrence on *veut* définir ces méthodes. Ça marcherait aussi mais ça me paraît pas le plus approprié, en tout cas au niveau de l'intention.

2022-02-04 17:40 UTC, durierem commented on lib/enginn/resource.rb
> +      # TODO: find a way to properly notice the user that the deletion succeeded
Je me suis permis de rajouter un `@errors` lorsqu'il y a une erreur avec ces méthodes. Pour l'instant j'ai juste mis dedans l'objet `Response` de Faraday. Ce n'est pas probablement pas le mieux. À rediscuter pour de futures améliorations je pense. Est-ce qu'on veut avoir des `@errors` avec les méthodes `!` aussi d'ailleurs ?

2022-02-04 17:41 UTC, durierem commented on lib/enginn/project.rb
> +      # TODO: replace `uid` with `id` when PK migration is completed
C'est bon (c545433)

2022-02-04 17:42 UTC, durierem commented on spec/enginn/client_spec.rb
> +  describe '#projects' do
C'est fait (2d58510)

2022-02-10 08:34 UTC, karquelf commented on lib/enginn/resource.rb
> +        self.class.define_method(attribute) { @attributes[attribute] }
Je suis d'accord avec toi Rémii, l'idée de `method_missing` est d'obliger les classes enfant à redéfinir ces méthodes. Mais dans notre cas c'est une même génération que l'on veut effectivement

2022-02-17 11:44 UTC, karquelf approved these changes

2022-02-17 11:48 UTC, karquelf commented
J'ai approve, c'est très cool ce qui a été fait

Je me pose éventuellement la question des Faraday::Error qui sont throw dans le cas de save! ou autre
est-ce qu'on ne veut pas catch ces erreurs pour ensuite en donner des plus custom à l'utilisateur du style, on catch les 404/401 et on lui throw des EnginnError::Unauthorized / 422 EnginnError::FailedRequest (pas forcément le bon nom de class mais l'idée est là)

2022-02-17 13:17 UTC, durierem commented
> est-ce qu'on ne veut pas catch ces erreurs pour ensuite en donner des plus custom à l'utilisateur

Je me suis également posé la question : les [erreurs Faraday](https://lostisland.github.io/faraday/middleware/raise-error) sont déjà nommées en fonction du code HTTP, ça me semblait ajouter du code pour pas grand chose.

Je n'en vois pas l'usage en tout cas. Peut-être à l'avenir ?

2022-02-18 16:54 UTC, karquelf commented
> > est-ce qu'on ne veut pas catch ces erreurs pour ensuite en donner des plus custom à l'utilisateur
> 
> Je me suis également posé la question : les [erreurs Faraday](https://lostisland.github.io/faraday/middleware/raise-error) sont déjà nommées en fonction du code HTTP, ça me semblait ajouter du code pour pas grand chose.
> 
> Je n'en vois pas l'usage en tout cas. Peut-être à l'avenir ?

C'était surtout pour personnifier un peu + les erreurs. J'ai l'impression que si j'utilise la gem enginn mais que j'ai une erreur faraday qui pop, que c'est la gem qui a potentiellement un soucis + que ce que j'ai fais moi dans son utilisation

2022-02-21 11:38 UTC, durierem commented
J'ai ajouté de quoi gérer des erreurs Enginn. En gros au lieu d'utiliser le middleware `raise_error` par défaut, on en utilise un custom (qui hérite de celui par défaut) qui lèves des erreurs `Enginn` à la place :

```rb
# lib/error.rb

class RaiseError < Faraday::Response::RaiseError
  # ...
end

Faraday::Response.register_middleware(enginn_raise_error: Enginn::RaiseError)

# lib/client.rb

def connection
  @connection do |conn|
    # ...
    conn.response :enginn_raise_error
    # ...
  end
end
```


On garde une classe d'erreur *standard* à Enginn au cas où
```rb
# lib/error.rb

class Error < StandardError; end
```

Toutes les autres erreurs héritent des erreurs Faraday mais on les place sous `Enginn::HTTPError` au lieu de `FaradayError`.
```rb
# lib/error.rb

class HTTPError < Faraday::Error; end
class ClientError < HTTPError; end
class ServerError < HTTPError; end
# ...
```
Ça permet par exemple de
```rb
begin
  # ...
rescue Enginn::HTTPError => e
  e.response
end
```

2022-02-22 08:54 UTC, karquelf commented
Ah yes c'est cool, c'est mieux que du rescue partout comme j'avais en tête à la base xD

Je me posais la question de regrouper certaines erreurs ensemble mais au final c'est une API qu'on utilise c'est surement mieux d'être assez explicite la dessus

2022-02-22 10:59 UTC, levraipixel approved these changes

2022-02-22 11:02 UTC, merged